### ISSUE TITLE
Remove validation annotations on protobuf messages

### ISSUE THREAD

**Issue by emilbayes** [vegaprotocol/protos#144]
In generating JS codecs for our protobuf messages I got stuck on the validation annotations. @jeremyletang told me that the annotations are largely unused, so #143 removes them from all messages and removes the dependency that was used to parse them.

**Comment by ashleyvega** [comment]
Any chance we can keep this and make it work?

These annotations get into docs, e.g. https://docs.fairground.vega.xyz/api/grpc/#vega.TargetStakeParameters (or search for `Validated Fields`.

**Comment by jeremyletang** [comment]
> Any chance we can keep this and make it work?
> 
> These annotations get into docs, e.g. https://docs.fairground.vega.xyz/api/grpc/#vega.TargetStakeParameters (or search for `Validated Fields`).

No the core really want to remove this. They are totally unused, and not supported with other language. I've had the same issue when compiling the code to Rust which could just not compile even if importing the go-validator code.

This is unused code, it just bring more dependency. Let's remove it. The point you mention are very much valid though (documentation), and that can be improve by adding more details to the fields about their constraints.

**Comment by barnabee** [comment]
Does this mean there would be some kind of doc updates needed to restore anything that would be lost in docs before this PR can be merged? Or a ticket raised somewhere for that if it's urgent to unblock @emilbayes?

**Comment by jeremyletang** [comment]
> Does this mean there would be some kind of doc updates needed to restore anything that would be lost in docs before this PR can be merged? Or a ticket raised somewhere for that if it's urgent to unblock @emilbayes?

We should open a ticket to address it soonish. Yes
