### ISSUE TITLE
Generate OpenAPI 3 API files

### ISSUE THREAD

**Issue by edd** [vegaprotocol/protos#229]
# Task Overview

**In order to** improve the way Docusaurus handles our REST documentation 
**We need** to use `buf` to generate OpenAPI v3 documentation as well as swagger documentation
**So that** we can try out https://github.com/cloud-annotations/docusaurus-openapi/

# Acceptance Criteria
How do we know when this technical task is complete:

- In a tagged release, there is a JSON or YAML file containing OpenAPI v3 specs for all APIs
# Additional Details (optional)
Any additional information including known dependacies, impacted components.

# Examples (optional)
Code snippets, API calls that could be used on dependant tasks.

**Comment by gordsport** [comment]
@edd - does this issue supersede https://github.com/vegaprotocol/vega/issues/5747 ?

**Comment by tguinot** [comment]
Open Api v3 seems to not be usable at the moment, which should not be a problem since we can get v2 to work with docusaurus
