### ISSUE TITLE
Uniform naming across service endpoints

### ISSUE THREAD

**Issue by emilbayes** [vegaprotocol/protos#274]
Over time our naming of rest endpoints and their corresponding services have drifted in naming convention. Examples:

Vega core exposes:

https://github.com/vegaprotocol/protos/blob/3e4accef56fa71ec3734a1f4b71af528d519c8bf/sources/vega/grpc-rest-bindings.yml#L31-L33

But in data node this is exposed as:

https://github.com/vegaprotocol/protos/blob/3e4accef56fa71ec3734a1f4b71af528d519c8bf/sources/data-node/grpc-rest-bindings.yml#L73-L75

Of note here is `ListNetworkParameters` vs `NetworkParameters`. I prefer the former, which makes it clear that a collection of items is returned and not a single item (which would be a `Get` prefix)

@jeremyletang also suggested that `TradingProxyService` may be more aptly named `CoreServiceProxy`

Another example is withdrawals:

https://github.com/vegaprotocol/protos/blob/3e4accef56fa71ec3734a1f4b71af528d519c8bf/sources/data-node/grpc-rest-bindings.yml#L103-L109

The first URL takes an `id`, but it's unclear which type of ID this is, compared to the next two endpoints, which clearly prefix their IDs. Another example is `party` and `party_id`, which is consumed by many endpoints.

My preference would be to clearly prefix all service endpoints by the action they perform, and clearly name all parameters with their type. 

I'm happy to submit a PR to this repo

**Comment by emilbayes** [comment]
Here are some more concrete examples of the changes I envision:

1. Adding verb prefixes to endpoints. Examples include:
`ListOrdersByMarket` and `GetOrderByMarketAndID`:
https://github.com/vegaprotocol/protos/blob/3e4accef56fa71ec3734a1f4b71af528d519c8bf/sources/data-node/grpc-rest-bindings.yml#L23-L26
`ListAssets` vs `GetAssetByID`:
https://github.com/vegaprotocol/protos/blob/3e4accef56fa71ec3734a1f4b71af528d519c8bf/sources/data-node/grpc-rest-bindings.yml#L35-L38
While I think "ephemeral" actions like these can stay the same:
https://github.com/vegaprotocol/protos/blob/3e4accef56fa71ec3734a1f4b71af528d519c8bf/sources/data-node/grpc-rest-bindings.yml#L64
https://github.com/vegaprotocol/protos/blob/3e4accef56fa71ec3734a1f4b71af528d519c8bf/sources/data-node/grpc-rest-bindings.yml#L69
Other endpoints are already named in this style, eg:
https://github.com/vegaprotocol/protos/blob/3e4accef56fa71ec3734a1f4b71af528d519c8bf/sources/data-node/grpc-rest-bindings.yml#L98-L101

2. Qualify ID's/references unambiguously. Examples include:
https://github.com/vegaprotocol/protos/blob/3e4accef56fa71ec3734a1f4b71af528d519c8bf/sources/data-node/grpc-rest-bindings.yml#L95
https://github.com/vegaprotocol/protos/blob/3e4accef56fa71ec3734a1f4b71af528d519c8bf/sources/data-node/grpc-rest-bindings.yml#L105
https://github.com/vegaprotocol/protos/blob/3e4accef56fa71ec3734a1f4b71af528d519c8bf/sources/data-node/grpc-rest-bindings.yml#L113
https://github.com/vegaprotocol/protos/blob/3e4accef56fa71ec3734a1f4b71af528d519c8bf/sources/data-node/grpc-rest-bindings.yml#L131
https://github.com/vegaprotocol/protos/blob/3e4accef56fa71ec3734a1f4b71af528d519c8bf/sources/data-node/grpc-rest-bindings.yml#L171

3. RESTify endpoint names:
https://github.com/vegaprotocol/protos/blob/3e4accef56fa71ec3734a1f4b71af528d519c8bf/sources/data-node/grpc-rest-bindings.yml#L39-L40
I'd change this to `/assets/{asset_id}/infrastructure-fee-accounts` (kebab case name, qualify id, missing plural)

**Comment by gordsport** [comment]
Closing as work that is being covered in:
- https://github.com/vegaprotocol/vega/issues/5685
