### ISSUE TITLE
Use optional in required place

### ISSUE THREAD

**Issue by jeremyletang** [vegaprotocol/protos#340]
We are now using a version of protobuf which can support optional.

Let's audit the codebase and replace all things like `StringValue` with optinal fields.

**Comment by emilbayes** [comment]
Perhaps this should be split in two issues.

Discussing V2 API for data-node, we identified many places where `optional` improved readability and clarified the intention. So this is underway in that regard. So perhaps we should split this into a "core" part and a GRPC part to make the "migration" easier?
