### ISSUE TITLE
Rename GetAssetBundleRequest

### ISSUE THREAD

**Issue by jeremyletang** [vegaprotocol/protos#435]
https://github.com/vegaprotocol/protos/blob/develop/sources/data-node/api/v2/trading_data.proto#L421

This provide the bundle for the ListAsset method, the call should be rename to reflect that (that doesn't sounds like much, but a new call will be require some day to DelistAsset too, so it'll make things easier).

**Comment by gordsport** [comment]
related to
- https://github.com/vegaprotocol/system-tests/issues/337
