### ISSUE TITLE
Market data API documentation doesn't reflect behavior for some fields

### ISSUE THREAD

**Issue by witgaw** [vegaprotocol/protos#478]
The market data API field descriptions don't always reflect the actual values being returned, e.g.:
From https://docs.fairground.vega.xyz/api/grpc/#vega.MarketData:

auction_start | int64 | &nbsp; | Time until next auction (used in FBA's) - currently always 0
-- | -- | -- | --

but in fact the field returns the start time of the current auction if market is in auction mode.

**Comment by gordsport** [comment]
Hey @candida-d,
I think the docs information is auto-generated from data-node/entities/marketdata.go - can you confirm if that is the case and I will get some one to check this and update to be correct.

**Comment by candida-d** [comment]
Hey @gordsport, I believe the actual source of truth for this is the protos, which then filters down to data-node. https://github.com/vegaprotocol/protos/blob/develop/sources/vega/vega.proto#L903

**Comment by candida-d** [comment]
@witgaw I've tackled your example in #524 but as we discussed, if you come across other examples let me know. If needed I can raise another PR to fix them. (This fix is for grpc/rest but not graphql... coming soon)
