### ISSUE TITLE
Voting with invalid proposal ID returns 500 and incorrect exception message 

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/protos#506]
We now see a test which submits a network param proposal and then a vote trx which references an invalid proposal.
Previously the core produced a TX Error event containing "Proposal error not found in TX_ERROR event"

Now the wallet API respond status code is 500 and the response text contains

failed to sign tx {"error":"Internal - vote_submission.market_id (should be a valid vega ID)"}

Did not expect the change but we can handle the wallet response if this is expected behaviour but the trx API should not return a 500 I think.

**Comment by jeremyletang** [comment]
Ths is expected behaviour, we've added validation on all transaction using IDs or pubkey to make sure they had the correct format.

**Comment by vega-paul** [comment]
The error mentions market_id but the proposal Id was invalid?

**Comment by jeremyletang** [comment]
ah right. that's a bad copy pasta. we'll fix

**Comment by vega-paul** [comment]
And should we expect to get a 500 on the command API response hdr?
