### ISSUE TITLE
Improve API documentation for AccountType

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/protos#523]
# AccountType description fields
The descriptions of the AccountType fields could use a little extra detail or more information. 

There has been some confusion in the community about the use of the term Account. In order to help with this and improve the API documentation generally its required that we update the API descriptions so the documentation site is clearer.

Some suggested wording regarding the margin account:

>When you trade on a market, the required initial margin is allocated to that market from your funds, meaning that it can't be withdrawn or used as margin on another market while it is allocated to the first market (note that the Vega protocol uses an internal accounting system to segregate funds held as margin from other funds to ensure they are never lost or "double spent" — read more [here](https://zombo.com/)).

@guoguojin - should @candida-d need any help in finding where some of the descriptions are held in datanode/protos please can you help direct to the correct locations?

**Comment by candida-d** [comment]
Closed in #472
